---
# _source: http://amobiz.github.io/2015/12/21/applying-eslint-using-atom-linter-eslint/
# _log:
#   - '2017-03-02: first edit'
#   - '2017-07-12: port from json to yaml; port to unify my favorite style along with work env'
#   - '2017-07-18': update with es6 style
#   - '2021-04-17': integrate with prettier v2
# _NOTE: copy this file to folder you want; rename it as .eslintrc.*; if possible reload text editor;
root: true
env:
  browser: true
  commonjs: true
  es6: true
  node: true
globals:
  atom: true
  describe: true
  it: true
extends:
  - 'eslint:recommended'
  - 'prettier'
parserOptions:
  ecmaVersion: 8
  sourceType: module
rules:
  no-console: off
  no-unused-vars:
  - warn
  - vars: all
    args: after-used
